public class ConflictCls {
    public static void fgg(){
        string ert;
         string ert1;
         string ert22;
         string ert3;
         string ert42;
         string ert5;
         string ert6;
         string ert7;
         string ert82;
         string ert9;
         string ert10;
         string ert112;
         string ert12;
         string ert132;
         string ert14;
         string ert152;
         string ert16;
         string ert172;
        
        
        
        
        string ert1732;
        
    }
}