public class ConflictCls {
    public static void fgg(){
        string ert; //
         string ert1;/////
         string ert2;
         string ert3;
         string ert4;
         string ert5;
         string ert6;
         string ert7;
         string ert8;
         string ert9;
         string ert10;
         string ert11;
         string ert12;
         string ert13;
         string ert14;
         string ert15;
         string ert16;
         string ert17;
         //added for rb
        
    }  
}